export const GET_APPOINMENT = 'GET_APPOINMENT';
export const GET_APPOINMENT_REQUEST = 'GET_APPOINMENT_REQUEST';
export const GET_APPOINMENT_ERROR = 'GET_APPOINMENT_ERROR';



export const GET_INSIGHTS = 'GET_INSIGHTS';
export const GET_INSIGHTS_REQUEST = 'GET_INSIGHTS_REQUEST';
export const GET_INSIGHTS_ERROR = 'GET_INSIGHTS_ERROR';