export const GET_ALL_EQUIPMENT = 'GET_ALL_EQUIPMENT';
export const GET_ALL_EQUIPMENT_REQUEST = 'GET_ALL_EQUIPMENT_REQUEST';
export const GET_ALL_EQUIPMENT_ERROR = 'GET_ALL_EQUIPMENT_ERROR';

export const GET_EQUIPMENT = 'GET_EQUIPMENT';
export const GET_EQUIPMENT_REQUEST = 'GET_EQUIPMENT_REQUEST';
export const GET_EQUIPMENT_ERROR = 'GET_EQUIPMENT_ERROR';

