export const GET_ALL_PAYMENT = 'GET_ALL_PAYMENT';
export const GET_ALL_PAYMENT_REQUEST = 'GET_ALL_PAYMENT_REQUEST';
export const GET_ALL_PAYMENT_ERROR = 'GET_ALL_PAYMENT_ERROR';

export const GET_PAYMENT = 'GET_PAYMENT';
export const GET_PAYMENT_REQUEST = 'GET_PAYMENT_REQUEST';
export const GET_PAYMENT_ERROR = 'GET_PAYMENT_ERROR';

export const GET_PAYMENT_BY_CLIENT = 'GET_PAYMENT_BY_CLIENT';
export const GET_PAYMENT_BY_CLIENT_REQUEST = 'GET_PAYMENT_BY_CLIENT_REQUEST';
export const GET_PAYMENT_BY_CLIENT_ERROR = 'GET_PAYMENT_BY_CLIENT_ERROR';

export const GET_PAYMENT_BY_INVOICE = 'GET_PAYMENT_BY_INVOICE';
export const GET_PAYMENT_BY_INVOICE_REQUEST = 'GET_PAYMENT_BY_INVOICE_REQUEST';
export const GET_PAYMENT_BY_INVOICE_ERROR = 'GET_PAYMENT_BY_INVOICE_ERROR';