export const GET_ALL_WORKORDER_STATUS = 'GET_ALL_WORKORDER_STATUS';
export const GET_ALL_WORKORDER_STATUS_REQUEST = 'GET_ALL_WORKORDER_STATUS_REQUEST';
export const GET_ALL_WORKORDER_STATUS_ERROR = 'GET_ALL_WORKORDER_STATUS_ERROR';
