export const GET_ALL_INVOICE = 'GET_ALL_INVOICE';
export const GET_ALL_INVOICE_REQUEST = 'GET_ALL_INVOICE_REQUEST';
export const GET_ALL_INVOICE_ERROR = 'GET_ALL_INVOICE_ERROR';

export const GET_INVOICE = 'GET_INVOICE';
export const GET_INVOICE_REQUEST = 'GET_INVOICE_REQUEST';
export const GET_INVOICE_ERROR = 'GET_INVOICE_ERROR';

export const GET_INVOICE_BY_CLIENT = 'GET_INVOICE_BY_CLIENT';
export const GET_INVOICE_BY_CLIENT_REQUEST = 'GET_INVOICE_BY_CLIENT_REQUEST';
export const GET_INVOICE_BY_CLIENT_ERROR = 'GET_INVOICE_BY_CLIENT_ERROR';

export const GET_INVOICE_BY_WORKORDER = 'GET_INVOICE_BY_WORKORDER';
export const GET_INVOICE_BY_WORKORDER_REQUEST = 'GET_INVOICE_BY_WORKORDER_REQUEST';
export const GET_INVOICE_BY_WORKORDER_ERROR = 'GET_INVOICE_BY_WORKORDER_ERROR';

