export const GET_ALL_CLIENT = 'GET_ALL_CLIENT';
export const GET_ALL_CLIENT_REQUEST = 'GET_ALL_CLIENT_REQUEST';
export const GET_ALL_CLIENT_ERROR = 'GET_ALL_CLIENT_ERROR';

export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_REQUEST = 'GET_CLIENT_REQUEST';
export const GET_CLIENT_ERROR = 'GET_CLIENT_ERROR';

