export const GET_ALL_SCHEDULE_TYPE = 'GET_ALL_SCHEDULE_TYPE';
export const GET_ALL_SCHEDULE_TYPE_REQUEST = 'GET_ALL_SCHEDULE_TYPE_REQUEST';
export const GET_ALL_SCHEDULE_TYPE_ERROR = 'GET_ALL_SCHEDULE_TYPE_ERROR';

export const GET_SCHEDULE_TYPE = 'GET_SCHEDULE_TYPE';
export const GET_SCHEDULE_TYPE_REQUEST = 'GET_SCHEDULE_TYPE_REQUEST';
export const GET_SCHEDULE_TYPE_ERROR = 'GET_SCHEDULE_TYPE_ERROR';

