export const GET_ALL_SCHEDULE = 'GET_ALL_SCHEDULE';
export const GET_ALL_SCHEDULE_REQUEST = 'GET_ALL_SCHEDULE_REQUEST';
export const GET_ALL_SCHEDULE_ERROR = 'GET_ALL_SCHEDULE_ERROR';


export const GET_ALL_SCHEDULE_BY_WORKORDER = 'GET_ALL_SCHEDULE_BY_WORKORDER';
export const GET_ALL_SCHEDULE_BY_WORKORDER_REQUEST = 'GET_ALL_SCHEDULE_BY_WORKORDER_REQUEST';
export const GET_ALL_SCHEDULE_BY_WORKORDER_ERROR = 'GET_ALL_SCHEDULE_BY_WORKORDER_ERROR';

export const GET_SCHEDULE = 'GET_SCHEDULE';
export const GET_SCHEDULE_REQUEST = 'GET_SCHEDULE_REQUEST';
export const GET_SCHEDULE_ERROR = 'GET_SCHEDULE_ERROR';

