export const GET_ALL_PURCHASE = 'GET_ALL_PURCHASE';
export const GET_ALL_PURCHASE_REQUEST = 'GET_ALL_PURCHASE_REQUEST';
export const GET_ALL_PURCHASE_ERROR = 'GET_ALL_PURCHASE_ERROR';

export const GET_PURCHASE = 'GET_PURCHASE';
export const GET_PURCHASE_REQUEST = 'GET_PURCHASE_REQUEST';
export const GET_PURCHASE_ERROR = 'GET_PURCHASE_ERROR';

export const GET_PURCHASE_BY_CLIENT = 'GET_PURCHASE_BY_CLIENT';
export const GET_PURCHASE_BY_CLIENT_REQUEST = 'GET_PURCHASE_BY_CLIENT_REQUEST';
export const GET_PURCHASE_BY_CLIENT_ERROR = 'GET_PURCHASE_BY_CLIENT_ERROR';

