export const GET_ALL_WORKORDER = 'GET_ALL_WORKORDER';
export const GET_ALL_WORKORDER_REQUEST = 'GET_ALL_WORKORDER_REQUEST';
export const GET_ALL_WORKORDER_ERROR = 'GET_ALL_WORKORDER_ERROR';

export const GET_ALL_WORKORDER_BY_CLIENT = 'GET_ALL_WORKORDER_BY_CLIENT';
export const GET_ALL_WORKORDER_BY_CLIENT_REQUEST = 'GET_ALL_WORKORDER_BY_CLIENT_REQUEST';
export const GET_ALL_WORKORDER_BY_CLIENT_ERROR = 'GET_ALL_WORKORDER_BY_CLIENT_ERROR';

export const GET_WORKORDER = 'GET_WORKORDER';
export const GET_WORKORDER_REQUEST = 'GET_WORKORDER_REQUEST';
export const GET_WORKORDER_ERROR = 'GET_WORKORDER_ERROR';

