export const GET_ALL_QRCODE = 'GET_ALL_QRCODE';
export const GET_ALL_QRCODE_REQUEST = 'GET_ALL_QRCODE_REQUEST';
export const GET_ALL_QRCODE_ERROR = 'GET_ALL_QRCODE_ERROR';

export const GET_QRCODE = 'GET_QRCODE';
export const GET_QRCODE_REQUEST = 'GET_QRCODE_REQUEST';
export const GET_QRCODE_ERROR = 'GET_QRCODE_ERROR';

export const GET_QRCODE_BY_CLIENT = 'GET_QRCODE_BY_CLIENT';
export const GET_QRCODE_BY_CLIENT_REQUEST = 'GET_QRCODE_BY_CLIENT_REQUEST';
export const GET_QRCODE_BY_CLIENT_ERROR = 'GET_QRCODE_BY_CLIENT_ERROR';

