name: Build Node.js Application

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  variables:
    DOCKER_IMAGE: ccq-app
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify your Node.js version

    # Step 3: Navigate to the API directory and install dependencies
    - name: Install Dependencies
      working-directory: ./API
      run: npm install

    # Step 4: Run tests
    - name: Run Tests
      working-directory: ./API
      run: npm test -- --forceExit

    # Step 5: build dockerfile
    - name: build Docker image
      script:
        - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .





